import { JetBrains_Mono, Patrick_Hand } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import localFont from "next/font/local";
import Footer from "@/components/footer";

const comicSans = localFont({
  src: [
    { path: '../assets/fonts/COMIC.woff', weight: '400', style: 'normal' },
    { path: '../assets/fonts/comici.woff', weight: '400', style: 'italic' },
    { path: '../assets/fonts/design.graffiti.comicsansmsgras.woff', weight: '700', style: 'normal' },
    { path: '../assets/fonts/comicz.woff', weight: '700', style: 'italic' },
  ],
  variable: '--font-comic-sans',
});

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  weights: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${jetBrainsMono.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
